version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: expense_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - expense-net

  minio:
    image: cgr.dev/chainguard/minio:latest
    container_name: expense_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - expense-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: expense_backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres
      - minio
    networks:
      - expense-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: expense_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - expense-net

volumes:
  pgdata:
  minio_data:

networks:
  expense-net:
    driver: bridge